# Result와 감동적인 만남
21.02.22

mood: 😄 😙

<! 공부하며 작성한 내용이며 틀린 내용이 있을 수 있습니다. >

## 오늘 한 것
- Result 타입 공부 
- initializer 공부 
- 사파리와 STEP1 진행 후 PR

---

## 문제점 / 고민한점
* 편리한 이니셜라이저란? 
* 클래스 내부의 열거형 접근에 관해
* 열거형의 위치에 따른 메모리적 차이

## 학습 내용
## Result

> A value that represents either a success or a failure, including an associated value in each case.

공식 문서의 설명에 보면,
각각의 경우에 연관값을 포함해서 성공과 실패를 나타내는 값이다. 
라고 나와있다.  

```swift
@frozen enum Result<Success, Failure> where Failure : Error
```
그리고 선언부를 보면 이렇게 선언 되어 있다. `Generic` 을 사용해서 구현된 `enum` 타입이고, Success 와 Failure 값을 가질 수 있다. 조건으로 이중 Failure 는 Error 타입이여야 한다. 

```swift
enum Snack {
    case chocolate, candy, jelly
}

enum SnackError: Error {
    case iDontWant
    case wrongValue
}

func takeInput() -> Result<Snack, SnackError> {
    
    guard let input = readLine() else {
        return .failure(.wrongValue)
    }
    switch input {
    case "초콜릿":
        return .success(.chocolate)
    case "사탕":
        return .success(.candy)
    case "젤리":
        return .success(.jelly)
    case "안먹고 싶어요":
        return .failure(.iDontWant)
    default:
        return .failure(.wrongValue)
    }
}

switch takeInput() {
case .success(let snack):
    print("\(snack)을 선택하셨습니다.")
case .failure(.iDontWant):
    print("선택을 거부하셨습니다.")
case .failure(.wrongValue):
    print("잘못된 입력 입니다.")
}
```

아까 내가 삽질 했던 코드를 Result 를 사용해서 변경해 보았다.
takeInPut 함수의 return 값을 Result 타입으로 설정하였고, 성공일 땐 Snack 타입을 가지고 실패일 땐 SnackError 를 가지는 방식으로 처리하였다.  
```swift
Result<Snack, SnackError>
```

함수 안에서 switch문을 사용해서 조건을 돌다가 맞는 조건일 때 성공인지 실패인지 여부를 판단한다. 이때 Result 가 enum 타입이기 때문에 점문법으로 접근하여 연관 값을 넣어주면 된다.
```swift
return .success(.chocolate)
```
그리고 아래있는 switch 문에서 함수를 실행시켜서 (나중에 변수나 상수에 넣어서 처리해 주어도 됨) case문으로 접근해서 어떤 값이 들어있는지에 따라서 다른 실행문을 만들어 줄 수 있다. 

위에서 작성했던 코드에 안 좋았던 점이 모두 보완되었다. 

그런데 만약에 우리가 실패 했을 때는 어떠한 행동도 하지 않을 것이고 성공했을 때만 작동하게 하고 싶다. 할 수 있을까? 있다!

### get 연산자 
Result는 get 이라는 메서드를 가지고 있다. get은 값이 .success 일 때만 값을 반환 하고 실패할 경우에는 에러를 던져준다. 

자 마지막에 있는 switch 문을 get을 이용해 바꿔보았다. 
```swift
if let snack = try? takeInput().get() {
    print("\(snack)을 선택하셨습니다.")
}
```
try? 를 붙이는 이유는 get 을 사용한 이후 부터, 저 아이도 에러를 던질 수 있어졌다. 에러를 던질지 아닐지 우리는 모르는 상태이기에 옵셔널을 붙여주고 if let 을 이용해서 바인딩도 해준다. else 구문을 만들지 않는 이상 이제 에러가 던져진다고 해도 갈 곳이 없어져서 처리를 하지 않게 되고 if 문 안의 코드는 잘 작동되기 때문에 성공한 값만 가져 올 때 사용할 수 있다. 

실패도 저장하고 싶다면 else를 사용하면 된다.

---
삽질을 하고 Result를 알게 되어서, Result 를 알게 된 순간이 너무나 감동이었다. (정말정말정말로)
공부하다 보니 Result에 있는 다른 활용법이 throwing closure 를 받는 것이라고 하는데, closure 에 관한 개념이 부족하여 이해하는데 시간이 좀 걸릴 것 같다. 이 부분은 나중에 다시 공부해 보면 좋겠다. 

initializer 부분이 너무 길어서 읽는 것 자체가 버겁다.🥲 내일 다시 열심히 읽어 봐야겠다. 
