# 🧪 오류를 테스트 하는 방법 
21.04.14.thur

mood: 😆 😴

<! 공부하며 작성한 내용이며 틀린 내용이 있을 수 있습니다. >

## 오늘 한 것
- STEP2 오토레이아웃 잘짝 잡기
- reusable sell 학습 활동

## 문제점 / 고민한점

---

## 학습 내용
### 🧪 오류를 테스트 하는 방법 

오류를 던지는 부분을 테스트를 통과하도록 작성하려면 어떻게 해야할까?

#### XCTAssertThrowsError() 를 이용하는 방법 
어떻게 사용하는 메서드인지 구현 부를 보자. 
```swift
func XCTAssertThrowsError<T>(_ expression: @autoclosure () throws -> T, _ message: @autoclosure () -> String = "", file: StaticString = #filePath, line: UInt = #line, _ errorHandler: (_ error: Error) -> Void = { _ in })
```
첫번째 파라미터로 (`@autoclosure`는 클로저가 아닌 식을 자동으로 클로저로 만들어 준다.) 표현식을 받는다. 

두번째 파라미터를 메세지를 받는다. 그런데 기본값이 공백으로 들어가 있다.

세번째 파라미터는 StaticString 이라는 타입의 file을 가진다. 이것도 `#filePath`가 기본값으로 설정되어 있다. 

네번째 파라미터는 라인으로 UInt 타입인데 기본값이 #line 으로 되어 있다. 

그리고 마지막 다섯번째 파라미터로 errorHandler 를 받는다. 

뭐가 많은데... 우선 다른건 잘 모르고 1번 5번 파라미터를 잘 넣으면 된다.
```swift
func test코드() throws {
    XCTAssertThrowsError(try 오류를던질수있는메서드(문제있는값)) { error in
        XCTAssertEqual(error as? MyError, MyError.assetLoadError)
    }
}
```
첫번째 파라미터의 오류를 던지는 구문을 적어주고, 마지막 클로저에서 error 를 받아와서 안에서 XCTAssertEqual 로 이 오류가 맞는지 비교하기. 

#### XCTFail() 을 이용하는 방법 

XCTFail() -> 항상 실패하는 테스트

```swift
func test코드 throws {
    do {
        try 오류를던질수있는메서드(문제있는값)
            XCTFail()
        } catch MyError.errorType(let key, let value) {
            print(print("\n key: \(key) \n value: \(value) \n"))
        } catch {
            XCTFail()
        }
    }
```
do catch 문을 이용해서 
잘못되게 실패해야하는데 성공하는 경우 XCTFail() 로 실패하게 할 수 있고 
다른 에러타입을 밷었을 경우에도 실패하게 테스트 코드를 짤 수 있다.

---
참고 자료 
[XCTAssertThrowsError 공식 문서](https://developer.apple.com/documentation/xctest/1500795-xctassertthrowserror)
[XCTFail 공식 문서](https://developer.apple.com/documentation/xctest/xctfail)
